//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class Products
    {
        public Products()
        {
            this.ProductSuppliers = new HashSet<ProductSuppliers>();
            this.WarehouseProducts = new HashSet<WarehouseProducts>();
        }
    
        public int Id { get; set; }
         [Required(ErrorMessage = "The Name is required!!!")]
         [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage = "Invalid Characters.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The Code is required!!!")]
        public string Code { get; set; }
        [Required(ErrorMessage = "The Price is required!!!")]
        [RegularExpression(@"^[0-9]?[0-9](.[0-9][0-9])$", ErrorMessage = "Invalid Characters.")]
        public string CostPrice { get; set; }
        [Required(ErrorMessage = "The Category is required!!!")]
        public int Category { get; set; }
        [Required(ErrorMessage = "The Brand is required!!!")]
        public int Brand { get; set; }
        [Required(ErrorMessage = "The Brand is required!!!")]
        public virtual Brand Brand1 { get; set; }
        [Required(ErrorMessage = "The Category is required!!!")]
        public virtual Category Category1 { get; set; }
        public virtual ICollection<ProductSuppliers> ProductSuppliers { get; set; }
        public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; }
    }
}
