//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductSuppliers = new HashSet<ProductSuppliers>();
            this.WarehouseProducts = new HashSet<WarehouseProducts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CostPrice { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
    
        public virtual Brand Brand1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual ICollection<ProductSuppliers> ProductSuppliers { get; set; }
        public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; }

    }
}
